"""secp256k1: A pure-Python ECDSA signing, extraction, and analysis library."""

__version__ = "0.4.0"

from bitcoin.field import inverse, sqrt, pow_mod, validate_non_negative
from bitcoin.curve import (
    Point,
    CurveBackend,
    NativeBackend,
    LibsecpBackend,
    GENERATOR,
    INFINITY,
    FIELD_PRIME,
    CURVE_ORDER,
    get_backend,
    set_backend,
    negate,
    add,
    double,
    multiply,
    is_on_curve,
    sqrt_field,
    parse_public_key,
    serialize_public_key,
    normalize,
    normalize_non_negative,
)
from bitcoin.encoding import (
    parse_sec,
    serialize_sec,
    encode_der,
    decode_der,
    encode_varint,
    decode_varint,
    sha256,
    hash256,
    hash160,
    tagged_hash,
    encode_hex,
    decode_hex,
    bytes_to_int,
    int_to_bytes,
)
from bitcoin.script import (
    parse_script,
    serialize_script,
    classify_script_pubkey,
    P2PK,
    P2PKH,
    P2SH,
    P2WPKH,
    P2WSH,
    P2TR,
)
from bitcoin.transaction import Tx, TxIn, TxOut, OutPoint, Witness, parse_tx, make_tx
from bitcoin.sighash import (
    sighash_legacy,
    sighash_segwit,
    sighash_taproot,
    SIGHASH_ALL,
    SIGHASH_NONE,
    SIGHASH_SINGLE,
    SIGHASH_ANYONECANPAY,
)
from bitcoin.signature import (
    Record,
    SignatureCollection,
    extract_signatures,
    linearize_signatures,
    verify_sig,
)
from bitcoin.psbt import Psbt, PsbtInput, PsbtOutput, parse_psbt, serialize_psbt
from bitcoin.exceptions import (
    NotInvertible,
    PointError,
    InvalidSignature,
    InvalidDerSignature,
    ParsingError,
)
from bitcoin.settings import settings

__all__ = [
    "CurveBackend",
    "CURVE_ORDER",
    "FIELD_PRIME",
    "GENERATOR",
    "INFINITY",
    "InvalidDerSignature",
    "InvalidSignature",
    "LibsecpBackend",
    "NativeBackend",
    "NotInvertible",
    "OutPoint",
    "P2PK",
    "P2PKH",
    "P2SH",
    "P2TR",
    "P2WPKH",
    "P2WSH",
    "ParsingError",
    "Point",
    "PointError",
    "Psbt",
    "PsbtInput",
    "PsbtOutput",
    "Record",
    "SignatureCollection",
    "SIGHASH_ALL",
    "SIGHASH_ANYONECANPAY",
    "SIGHASH_NONE",
    "SIGHASH_SINGLE",
    "Tx",
    "TxIn",
    "TxOut",
    "Witness",
    "add",
    "bytes_to_int",
    "classify_script_pubkey",
    "decode_der",
    "decode_hex",
    "decode_varint",
    "double",
    "encode_der",
    "encode_hex",
    "encode_varint",
    "extract_signatures",
    "get_backend",
    "hash160",
    "hash256",
    "int_to_bytes",
    "inverse",
    "is_on_curve",
    "linearize_signatures",
    "make_tx",
    "multiply",
    "negate",
    "normalize",
    "normalize_non_negative",
    "parse_psbt",
    "parse_public_key",
    "parse_sec",
    "parse_script",
    "parse_tx",
    "pow_mod",
    "serialize_psbt",
    "serialize_public_key",
    "serialize_sec",
    "serialize_script",
    "set_backend",
    "settings",
    "sha256",
    "sighash_legacy",
    "sighash_segwit",
    "sighash_taproot",
    "sqrt",
    "sqrt_field",
    "tagged_hash",
    "validate_non_negative",
    "verify_sig",
]
